#!/usr/bin/python3

import csv
import matplotlib.pyplot as pyplot
import sys


data = csv.reader(sys.stdin)

x = []
y = []

[iterations, parameter] = next(data)
parameter = float(parameter)
filename = 'graph_{:f}.png'.format(parameter)

for [x_str, y_str] in data:
    x.append(float(x_str))
    y.append(float(y_str))

sys.stdin.close()

[p] = pyplot.plot(x, y)
p.set_marker('.')
p.set_markersize(1.0)
p.set_linestyle('')

pyplot.axis([0.0, 1.0, 0.0, 1.0])
pyplot.title('Parameter={:f}'.format(parameter))
pyplot.savefig(filename)


